apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJabXgxWm1aNVltOXVaVHBuYUhCZk5WTnlNRlE0ZG5wVk5YcHFibXR1YVRoWlFqUXdORVptWVVWSE9IRnlNbU5xT1dwTyIKICB9Cn0sCiAgImNyZWRzU3RvcmUiOiAib3N4a2V5Y2hhaW4iLAogICJjdXJyZW50Q29udGV4dCI6ICJvcmJzdGFjayIsCiAgImZlYXR1cmVzIjogewogICAgImhvb2tzIjogInRydWUiCiAgfSwKICAicGx1Z2lucyI6IHsKICAgICJkZWJ1ZyI6IHsKICAgICAgImhvb2tzIjogImV4ZWMiCiAgICB9LAogICAgInNjb3V0IjogewogICAgICAiaG9va3MiOiAicHVsbCxidWlsZHggYnVpbGQiCiAgICB9CiAgfQp9Cg==
type: kubernetes.io/dockerconfigjson
